flightapp.server_url = localhost
flightapp.server_port = OUTPUT_FROM_`id -u`_HERE
flightapp.database_name = flights
flightapp.username = UWNETID_HERE
flightapp.password = IHeartFlights
flightapp.tablename_suffix = UWNETID_HERE